### ISSUE TITLE
Unpublished components inside Composite renderings

### ISSUE THREAD

**Issue by cabakon** [csteeg/BoC.Sitecore.CompositeComponents#1]
Hello, did you have some issues with this, when you had an unpublished component inside your Composite rendering? 

I have an error in the last part:
PipelineService.Get().RunPipeline()

Error:
The model item passed into the dictionary is of type 'Sitecore.Mvc.Presentation.RenderingModel', but this dictionary requires a model item of type 'MyType'.

thx

**Comment by csteeg** [comment]
Hmm, no. but are you sure the component works outside a composite rendering?

**Comment by cabakon** [comment]
It does. The problem was in more nested components. Resolved, thanks
